
//  Copyright (c) Comodo Group Inc. by 2013
//  
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//  
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//  
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//  
//  
// This file is automatically generated from the following source files:
// Command line options: 
//     /dlexer=False
//     /dparser=False
//     /dstack=False

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Goedel.Registry;


//
// Namespace GoedelDomainer
// Class Domainer
//


// Types
//   TopTypeType
//       Group
//       RR
//       Q
//       IG
//       NA
//   TypeType
//       Obsolete
//       Pseudo
//       Experimental
//       IPv4
//       IPv6
//       Domain
//       Mail
//       NodeID
//       Byte
//       Int16
//       Int32
//       Time32
//       Time48
//       String
//       Strings
//       OptionalString
//       StringX
//       Binary
//       Binary8
//       Binary16
//       LBinary
//       Hex
//       Hex8
//       Hex16
//       List
//       Alt
//       LByte
//       LInt16
//       OptionList
//       Gateway
//       Null
//       AltEntry
//   IdType
//       GroupT
//       RRT
//   NamespaceType
//       GoedelDomainer
//   ClassType
//       Domainer
//   NameType
//       Id
//       Members
//       Code
//       Description
//       Reference
//       Entries
//       Length
//       Target
//       Choices
//       Reason
//       First
//       Last
//   TokenType
//       VarT
//       ReasonT

namespace GoedelDomainer {


    public enum DomainerType {
        _Top,

        Group,
        RR,
        Obsolete,
        Pseudo,
        Experimental,
        IPv4,
        IPv6,
        Domain,
        Mail,
        NodeID,
        Byte,
        Int16,
        Int32,
        Time32,
        Time48,
        String,
        OptionalString,
        Strings,
        StringX,
        Binary,
        Binary8,
        Binary16,
        LBinary,
        LByte,
        LInt16,
        Hex,
        Hex8,
        Hex16,
        Null,
        OptionList,
        Gateway,
        List,
        Alt,
        AltEntry,
        Q,
        IG,
        NA,

        _Label,
        _Bottom
        }    
    

    public abstract partial class _Choice {
        abstract public DomainerType _Tag ();

		public abstract void Serialize (StructureWriter Output, bool tag);
        }



    public partial class Group : _Choice {
        public ID<_Choice>				Id; 
        public List <REF<_Choice>>           Members = new List<REF<_Choice>> ();

        public override DomainerType _Tag () {
            return DomainerType.Group;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Group");
				}

	        Output.WriteId ("Id", Id.ToString()); 
			Output.StartList ("");
			foreach (REF<_Choice> _e in Members) {
				Output.WriteId ("Members", _e.ToString());
				}
			Output.EndList ("");
			if (tag) {
				Output.EndElement ("Group");
				}			
			}
		}

    public partial class RR : _Choice {
        public ID<_Choice>				Id; 
		public int						Code;
		public string					Description;
		public string					Reference;
        public List <_Choice>           Entries = new List<_Choice> ();

        public override DomainerType _Tag () {
            return DomainerType.RR;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("RR");
				}

	        Output.WriteId ("Id", Id.ToString()); 
			Output.WriteAttribute ("Code", Code);
			Output.WriteAttribute ("Description", Description);
			Output.WriteAttribute ("Reference", Reference);
			Output.StartList ("");
			foreach (_Choice _e in Entries) {
				_e.Serialize (Output, true);
				}
			Output.EndList ("");
			if (tag) {
				Output.EndElement ("RR");
				}			
			}
		}

    public partial class Obsolete : _Choice {

        public override DomainerType _Tag () {
            return DomainerType.Obsolete;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Obsolete");
				}

			if (tag) {
				Output.EndElement ("Obsolete");
				}			
			}
		}

    public partial class Pseudo : _Choice {

        public override DomainerType _Tag () {
            return DomainerType.Pseudo;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Pseudo");
				}

			if (tag) {
				Output.EndElement ("Pseudo");
				}			
			}
		}

    public partial class Experimental : _Choice {

        public override DomainerType _Tag () {
            return DomainerType.Experimental;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Experimental");
				}

			if (tag) {
				Output.EndElement ("Experimental");
				}			
			}
		}

    public partial class IPv4 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.IPv4;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("IPv4");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("IPv4");
				}			
			}
		}

    public partial class IPv6 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.IPv6;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("IPv6");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("IPv6");
				}			
			}
		}

    public partial class Domain : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Domain;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Domain");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Domain");
				}			
			}
		}

    public partial class Mail : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Mail;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Mail");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Mail");
				}			
			}
		}

    public partial class NodeID : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.NodeID;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("NodeID");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("NodeID");
				}			
			}
		}

    public partial class Byte : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Byte;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Byte");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Byte");
				}			
			}
		}

    public partial class Int16 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Int16;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Int16");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Int16");
				}			
			}
		}

    public partial class Int32 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Int32;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Int32");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Int32");
				}			
			}
		}

    public partial class Time32 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Time32;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Time32");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Time32");
				}			
			}
		}

    public partial class Time48 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Time48;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Time48");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Time48");
				}			
			}
		}

    public partial class String : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.String;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("String");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("String");
				}			
			}
		}

    public partial class OptionalString : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.OptionalString;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("OptionalString");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("OptionalString");
				}			
			}
		}

    public partial class Strings : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Strings;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Strings");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Strings");
				}			
			}
		}

    public partial class StringX : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.StringX;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("StringX");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("StringX");
				}			
			}
		}

    public partial class Binary : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Binary;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Binary");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Binary");
				}			
			}
		}

    public partial class Binary8 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Binary8;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Binary8");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Binary8");
				}			
			}
		}

    public partial class Binary16 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Binary16;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Binary16");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Binary16");
				}			
			}
		}

    public partial class LBinary : _Choice {
        public TOKEN<_Choice>			Length;
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.LBinary;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("LBinary");
				}

	        Output.WriteId ("Length", Length.ToString());
	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("LBinary");
				}			
			}
		}

    public partial class LByte : _Choice {
        public TOKEN<_Choice>			Target;
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.LByte;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("LByte");
				}

	        Output.WriteId ("Target", Target.ToString());
	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("LByte");
				}			
			}
		}

    public partial class LInt16 : _Choice {
        public TOKEN<_Choice>			Target;
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.LInt16;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("LInt16");
				}

	        Output.WriteId ("Target", Target.ToString());
	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("LInt16");
				}			
			}
		}

    public partial class Hex : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Hex;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Hex");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Hex");
				}			
			}
		}

    public partial class Hex8 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Hex8;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Hex8");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Hex8");
				}			
			}
		}

    public partial class Hex16 : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Hex16;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Hex16");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Hex16");
				}			
			}
		}

    public partial class Null : _Choice {

        public override DomainerType _Tag () {
            return DomainerType.Null;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Null");
				}

			if (tag) {
				Output.EndElement ("Null");
				}			
			}
		}

    public partial class OptionList : _Choice {
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.OptionList;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("OptionList");
				}

	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("OptionList");
				}			
			}
		}

    public partial class Gateway : _Choice {
        public TOKEN<_Choice>			Code;
        public TOKEN<_Choice>			Id;

        public override DomainerType _Tag () {
            return DomainerType.Gateway;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Gateway");
				}

	        Output.WriteId ("Code", Code.ToString());
	        Output.WriteId ("Id", Id.ToString());
			if (tag) {
				Output.EndElement ("Gateway");
				}			
			}
		}

    public partial class List : _Choice {
        public TOKEN<_Choice>			Id;
        public List <_Choice>           Entries = new List<_Choice> ();

        public override DomainerType _Tag () {
            return DomainerType.List;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("List");
				}

	        Output.WriteId ("Id", Id.ToString());
			Output.StartList ("");
			foreach (_Choice _e in Entries) {
				_e.Serialize (Output, true);
				}
			Output.EndList ("");
			if (tag) {
				Output.EndElement ("List");
				}			
			}
		}

    public partial class Alt : _Choice {
        public TOKEN<_Choice>			Id;
        public List <AltEntry>           Entries = new List<AltEntry> ();

        public override DomainerType _Tag () {
            return DomainerType.Alt;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Alt");
				}

	        Output.WriteId ("Id", Id.ToString());
			Output.StartList ("");
			foreach (AltEntry _e in Entries) {
				_e.Serialize (Output, true);
				}
			Output.EndList ("");
			if (tag) {
				Output.EndElement ("Alt");
				}			
			}
		}

    public partial class AltEntry : _Choice {
		public int						Code;
        public _Choice					Choices;

        public override DomainerType _Tag () {
            return DomainerType.AltEntry;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("AltEntry");
				}

			Output.WriteAttribute ("Code", Code);
	        Choices.Serialize (Output, true);
			if (tag) {
				Output.EndElement ("AltEntry");
				}			
			}
		}

    public partial class Q : _Choice {
        public ID<_Choice>				Id; 
		public int						Code;
		public string					Description;
		public string					Reference;

        public override DomainerType _Tag () {
            return DomainerType.Q;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("Q");
				}

	        Output.WriteId ("Id", Id.ToString()); 
			Output.WriteAttribute ("Code", Code);
			Output.WriteAttribute ("Description", Description);
			Output.WriteAttribute ("Reference", Reference);
			if (tag) {
				Output.EndElement ("Q");
				}			
			}
		}

    public partial class IG : _Choice {
        public ID<_Choice>				Id; 
		public int						Code;
		public string					Description;
		public string					Reference;

        public override DomainerType _Tag () {
            return DomainerType.IG;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("IG");
				}

	        Output.WriteId ("Id", Id.ToString()); 
			Output.WriteAttribute ("Code", Code);
			Output.WriteAttribute ("Description", Description);
			Output.WriteAttribute ("Reference", Reference);
			if (tag) {
				Output.EndElement ("IG");
				}			
			}
		}

    public partial class NA : _Choice {
        public TOKEN<_Choice>			Reason;
		public int						First;
		public int						Last;

        public override DomainerType _Tag () {
            return DomainerType.NA;
            }

		public override void Serialize (StructureWriter Output, bool tag) {

			if (tag) {
				Output.StartElement ("NA");
				}

	        Output.WriteId ("Reason", Reason.ToString());
			Output.WriteAttribute ("First", First);
			Output.WriteAttribute ("Last", Last);
			if (tag) {
				Output.EndElement ("NA");
				}			
			}
		}

    class _Label : _Choice {
        public REF<_Choice>            Label;

		// This method is never called. It exists only to prevent a warning when a
		// Schema does not contain a ChoiceREF element.
        public void Reach() {
            Label = null;
            }

        public override DomainerType _Tag () {
            return DomainerType._Label;
            }

		public override void Serialize (StructureWriter Output, bool tag) {
			Output.WriteId ("ID", Label.ToString());
			}
        }
//	}

//namespace Goedel.Registry {

    public enum StateCode {  
        _Start,
        _Choice,
        _End,

		Group_Start,
		Group__Id,				
		Group__Members,				
		RR_Start,
		RR__Id,				
		RR__Code,				
		RR__Description,				
		RR__Reference,				
		RR__Entries,				
		Obsolete_Start,
		Pseudo_Start,
		Experimental_Start,
		IPv4_Start,
		IPv4__Id,				
		IPv6_Start,
		IPv6__Id,				
		Domain_Start,
		Domain__Id,				
		Mail_Start,
		Mail__Id,				
		NodeID_Start,
		NodeID__Id,				
		Byte_Start,
		Byte__Id,				
		Int16_Start,
		Int16__Id,				
		Int32_Start,
		Int32__Id,				
		Time32_Start,
		Time32__Id,				
		Time48_Start,
		Time48__Id,				
		String_Start,
		String__Id,				
		OptionalString_Start,
		OptionalString__Id,				
		Strings_Start,
		Strings__Id,				
		StringX_Start,
		StringX__Id,				
		Binary_Start,
		Binary__Id,				
		Binary8_Start,
		Binary8__Id,				
		Binary16_Start,
		Binary16__Id,				
		LBinary_Start,
		LBinary__Length,				
		LBinary__Id,				
		LByte_Start,
		LByte__Target,				
		LByte__Id,				
		LInt16_Start,
		LInt16__Target,				
		LInt16__Id,				
		Hex_Start,
		Hex__Id,				
		Hex8_Start,
		Hex8__Id,				
		Hex16_Start,
		Hex16__Id,				
		Null_Start,
		OptionList_Start,
		OptionList__Id,				
		Gateway_Start,
		Gateway__Code,				
		Gateway__Id,				
		List_Start,
		List__Id,				
		List__Entries,				
		Alt_Start,
		Alt__Id,				
		Alt__Entries,				
		AltEntry_Start,
		AltEntry__Code,				
		AltEntry__Choices,				
		Q_Start,
		Q__Id,				
		Q__Code,				
		Q__Description,				
		Q__Reference,				
		IG_Start,
		IG__Id,				
		IG__Code,				
		IG__Description,				
		IG__Reference,				
		NA_Start,
		NA__Reason,				
		NA__First,				
		NA__Last,				
        }


    struct _StackItem {
        public StateCode   State;
        public GoedelDomainer._Choice     Token;
        }

    public partial class Domainer : Goedel.Registry.Parser{
        public List <GoedelDomainer._Choice>        Top;
        public Registry	<GoedelDomainer._Choice>	Registry;



        bool _StartOfEntry;
        public bool StartOfEntry {
            get {return _StartOfEntry;}
            private set { _StartOfEntry = value; }
            }

        StateCode								State;
        GoedelDomainer._Choice				Current;
        List <_StackItem>						Stack;
        TokenType								CurrentToken;
        Position								CurrentPosition;
        string									CurrentText;


        public static Domainer Parse(string File, Goedel.Registry.Dispatch Options) {
            var Result = new Domainer();
            Result.Options = Options;

            using (Stream infile =
                        new FileStream(File, FileMode.Open, FileAccess.Read)) {
                Lexer Schema = new Lexer(File);
                Schema.Process(infile, Result);
                }

            return Result;
            }


        public Domainer() {
            Top = new List<GoedelDomainer._Choice> () ;
            Registry = new Registry <GoedelDomainer._Choice> ();
            State = StateCode._Start;
            Stack = new List <_StackItem> ();
            _StartOfEntry = true;

			TYPE__GroupT = Registry.TYPE ("GroupT"); 
			TYPE__RRT = Registry.TYPE ("RRT"); 
			TYPE__VarT = Registry.TYPE ("VarT"); 
			TYPE__ReasonT = Registry.TYPE ("ReasonT"); 



            }



        public TYPE<GoedelDomainer._Choice> TYPE__GroupT ;
        public TYPE<GoedelDomainer._Choice> TYPE__RRT ;
        public TYPE<GoedelDomainer._Choice> TYPE__VarT ;
        public TYPE<GoedelDomainer._Choice> TYPE__ReasonT ;

        private GoedelDomainer._Choice New_Choice(string Label) {
            switch (Label) {

                case "Group": return NewGroup();
                case "RR": return NewRR();
                case "Obsolete": return NewObsolete();
                case "Pseudo": return NewPseudo();
                case "Experimental": return NewExperimental();
                case "IPv4": return NewIPv4();
                case "IPv6": return NewIPv6();
                case "Domain": return NewDomain();
                case "Mail": return NewMail();
                case "NodeID": return NewNodeID();
                case "Byte": return NewByte();
                case "Int16": return NewInt16();
                case "Int32": return NewInt32();
                case "Time32": return NewTime32();
                case "Time48": return NewTime48();
                case "String": return NewString();
                case "OptionalString": return NewOptionalString();
                case "Strings": return NewStrings();
                case "StringX": return NewStringX();
                case "Binary": return NewBinary();
                case "Binary8": return NewBinary8();
                case "Binary16": return NewBinary16();
                case "LBinary": return NewLBinary();
                case "LByte": return NewLByte();
                case "LInt16": return NewLInt16();
                case "Hex": return NewHex();
                case "Hex8": return NewHex8();
                case "Hex16": return NewHex16();
                case "Null": return NewNull();
                case "OptionList": return NewOptionList();
                case "Gateway": return NewGateway();
                case "List": return NewList();
                case "Alt": return NewAlt();
                case "AltEntry": return NewAltEntry();
                case "Q": return NewQ();
                case "IG": return NewIG();
                case "NA": return NewNA();

				}
            throw new System.Exception ("Reserved word not recognized \"" + Label + "\"");
            }



        private GoedelDomainer.Group NewGroup() {
            GoedelDomainer.Group result = new GoedelDomainer.Group();
            Push (result);
            State = StateCode.Group_Start;
            return result;
            }


        private GoedelDomainer.RR NewRR() {
            GoedelDomainer.RR result = new GoedelDomainer.RR();
            Push (result);
            State = StateCode.RR_Start;
            return result;
            }


        private GoedelDomainer.Obsolete NewObsolete() {
            GoedelDomainer.Obsolete result = new GoedelDomainer.Obsolete();
            Push (result);
            State = StateCode.Obsolete_Start;
            return result;
            }


        private GoedelDomainer.Pseudo NewPseudo() {
            GoedelDomainer.Pseudo result = new GoedelDomainer.Pseudo();
            Push (result);
            State = StateCode.Pseudo_Start;
            return result;
            }


        private GoedelDomainer.Experimental NewExperimental() {
            GoedelDomainer.Experimental result = new GoedelDomainer.Experimental();
            Push (result);
            State = StateCode.Experimental_Start;
            return result;
            }


        private GoedelDomainer.IPv4 NewIPv4() {
            GoedelDomainer.IPv4 result = new GoedelDomainer.IPv4();
            Push (result);
            State = StateCode.IPv4_Start;
            return result;
            }


        private GoedelDomainer.IPv6 NewIPv6() {
            GoedelDomainer.IPv6 result = new GoedelDomainer.IPv6();
            Push (result);
            State = StateCode.IPv6_Start;
            return result;
            }


        private GoedelDomainer.Domain NewDomain() {
            GoedelDomainer.Domain result = new GoedelDomainer.Domain();
            Push (result);
            State = StateCode.Domain_Start;
            return result;
            }


        private GoedelDomainer.Mail NewMail() {
            GoedelDomainer.Mail result = new GoedelDomainer.Mail();
            Push (result);
            State = StateCode.Mail_Start;
            return result;
            }


        private GoedelDomainer.NodeID NewNodeID() {
            GoedelDomainer.NodeID result = new GoedelDomainer.NodeID();
            Push (result);
            State = StateCode.NodeID_Start;
            return result;
            }


        private GoedelDomainer.Byte NewByte() {
            GoedelDomainer.Byte result = new GoedelDomainer.Byte();
            Push (result);
            State = StateCode.Byte_Start;
            return result;
            }


        private GoedelDomainer.Int16 NewInt16() {
            GoedelDomainer.Int16 result = new GoedelDomainer.Int16();
            Push (result);
            State = StateCode.Int16_Start;
            return result;
            }


        private GoedelDomainer.Int32 NewInt32() {
            GoedelDomainer.Int32 result = new GoedelDomainer.Int32();
            Push (result);
            State = StateCode.Int32_Start;
            return result;
            }


        private GoedelDomainer.Time32 NewTime32() {
            GoedelDomainer.Time32 result = new GoedelDomainer.Time32();
            Push (result);
            State = StateCode.Time32_Start;
            return result;
            }


        private GoedelDomainer.Time48 NewTime48() {
            GoedelDomainer.Time48 result = new GoedelDomainer.Time48();
            Push (result);
            State = StateCode.Time48_Start;
            return result;
            }


        private GoedelDomainer.String NewString() {
            GoedelDomainer.String result = new GoedelDomainer.String();
            Push (result);
            State = StateCode.String_Start;
            return result;
            }


        private GoedelDomainer.OptionalString NewOptionalString() {
            GoedelDomainer.OptionalString result = new GoedelDomainer.OptionalString();
            Push (result);
            State = StateCode.OptionalString_Start;
            return result;
            }


        private GoedelDomainer.Strings NewStrings() {
            GoedelDomainer.Strings result = new GoedelDomainer.Strings();
            Push (result);
            State = StateCode.Strings_Start;
            return result;
            }


        private GoedelDomainer.StringX NewStringX() {
            GoedelDomainer.StringX result = new GoedelDomainer.StringX();
            Push (result);
            State = StateCode.StringX_Start;
            return result;
            }


        private GoedelDomainer.Binary NewBinary() {
            GoedelDomainer.Binary result = new GoedelDomainer.Binary();
            Push (result);
            State = StateCode.Binary_Start;
            return result;
            }


        private GoedelDomainer.Binary8 NewBinary8() {
            GoedelDomainer.Binary8 result = new GoedelDomainer.Binary8();
            Push (result);
            State = StateCode.Binary8_Start;
            return result;
            }


        private GoedelDomainer.Binary16 NewBinary16() {
            GoedelDomainer.Binary16 result = new GoedelDomainer.Binary16();
            Push (result);
            State = StateCode.Binary16_Start;
            return result;
            }


        private GoedelDomainer.LBinary NewLBinary() {
            GoedelDomainer.LBinary result = new GoedelDomainer.LBinary();
            Push (result);
            State = StateCode.LBinary_Start;
            return result;
            }


        private GoedelDomainer.LByte NewLByte() {
            GoedelDomainer.LByte result = new GoedelDomainer.LByte();
            Push (result);
            State = StateCode.LByte_Start;
            return result;
            }


        private GoedelDomainer.LInt16 NewLInt16() {
            GoedelDomainer.LInt16 result = new GoedelDomainer.LInt16();
            Push (result);
            State = StateCode.LInt16_Start;
            return result;
            }


        private GoedelDomainer.Hex NewHex() {
            GoedelDomainer.Hex result = new GoedelDomainer.Hex();
            Push (result);
            State = StateCode.Hex_Start;
            return result;
            }


        private GoedelDomainer.Hex8 NewHex8() {
            GoedelDomainer.Hex8 result = new GoedelDomainer.Hex8();
            Push (result);
            State = StateCode.Hex8_Start;
            return result;
            }


        private GoedelDomainer.Hex16 NewHex16() {
            GoedelDomainer.Hex16 result = new GoedelDomainer.Hex16();
            Push (result);
            State = StateCode.Hex16_Start;
            return result;
            }


        private GoedelDomainer.Null NewNull() {
            GoedelDomainer.Null result = new GoedelDomainer.Null();
            Push (result);
            State = StateCode.Null_Start;
            return result;
            }


        private GoedelDomainer.OptionList NewOptionList() {
            GoedelDomainer.OptionList result = new GoedelDomainer.OptionList();
            Push (result);
            State = StateCode.OptionList_Start;
            return result;
            }


        private GoedelDomainer.Gateway NewGateway() {
            GoedelDomainer.Gateway result = new GoedelDomainer.Gateway();
            Push (result);
            State = StateCode.Gateway_Start;
            return result;
            }


        private GoedelDomainer.List NewList() {
            GoedelDomainer.List result = new GoedelDomainer.List();
            Push (result);
            State = StateCode.List_Start;
            return result;
            }


        private GoedelDomainer.Alt NewAlt() {
            GoedelDomainer.Alt result = new GoedelDomainer.Alt();
            Push (result);
            State = StateCode.Alt_Start;
            return result;
            }


        private GoedelDomainer.AltEntry NewAltEntry() {
            GoedelDomainer.AltEntry result = new GoedelDomainer.AltEntry();
            Push (result);
            State = StateCode.AltEntry_Start;
            return result;
            }


        private GoedelDomainer.Q NewQ() {
            GoedelDomainer.Q result = new GoedelDomainer.Q();
            Push (result);
            State = StateCode.Q_Start;
            return result;
            }


        private GoedelDomainer.IG NewIG() {
            GoedelDomainer.IG result = new GoedelDomainer.IG();
            Push (result);
            State = StateCode.IG_Start;
            return result;
            }


        private GoedelDomainer.NA NewNA() {
            GoedelDomainer.NA result = new GoedelDomainer.NA();
            Push (result);
            State = StateCode.NA_Start;
            return result;
            }


        static GoedelDomainer.DomainerType _Reserved(string Label) {
            switch (Label) {

                case "Group": return GoedelDomainer.DomainerType.Group;
                case "RR": return GoedelDomainer.DomainerType.RR;
                case "Obsolete": return GoedelDomainer.DomainerType.Obsolete;
                case "Pseudo": return GoedelDomainer.DomainerType.Pseudo;
                case "Experimental": return GoedelDomainer.DomainerType.Experimental;
                case "IPv4": return GoedelDomainer.DomainerType.IPv4;
                case "IPv6": return GoedelDomainer.DomainerType.IPv6;
                case "Domain": return GoedelDomainer.DomainerType.Domain;
                case "Mail": return GoedelDomainer.DomainerType.Mail;
                case "NodeID": return GoedelDomainer.DomainerType.NodeID;
                case "Byte": return GoedelDomainer.DomainerType.Byte;
                case "Int16": return GoedelDomainer.DomainerType.Int16;
                case "Int32": return GoedelDomainer.DomainerType.Int32;
                case "Time32": return GoedelDomainer.DomainerType.Time32;
                case "Time48": return GoedelDomainer.DomainerType.Time48;
                case "String": return GoedelDomainer.DomainerType.String;
                case "OptionalString": return GoedelDomainer.DomainerType.OptionalString;
                case "Strings": return GoedelDomainer.DomainerType.Strings;
                case "StringX": return GoedelDomainer.DomainerType.StringX;
                case "Binary": return GoedelDomainer.DomainerType.Binary;
                case "Binary8": return GoedelDomainer.DomainerType.Binary8;
                case "Binary16": return GoedelDomainer.DomainerType.Binary16;
                case "LBinary": return GoedelDomainer.DomainerType.LBinary;
                case "LByte": return GoedelDomainer.DomainerType.LByte;
                case "LInt16": return GoedelDomainer.DomainerType.LInt16;
                case "Hex": return GoedelDomainer.DomainerType.Hex;
                case "Hex8": return GoedelDomainer.DomainerType.Hex8;
                case "Hex16": return GoedelDomainer.DomainerType.Hex16;
                case "Null": return GoedelDomainer.DomainerType.Null;
                case "OptionList": return GoedelDomainer.DomainerType.OptionList;
                case "Gateway": return GoedelDomainer.DomainerType.Gateway;
                case "List": return GoedelDomainer.DomainerType.List;
                case "Alt": return GoedelDomainer.DomainerType.Alt;
                case "AltEntry": return GoedelDomainer.DomainerType.AltEntry;
                case "Q": return GoedelDomainer.DomainerType.Q;
                case "IG": return GoedelDomainer.DomainerType.IG;
                case "NA": return GoedelDomainer.DomainerType.NA;

                }
            return GoedelDomainer.DomainerType._Bottom;
            }


		public void Serialize (TextWriter Output) {
			Serialize (Output, OutputFormat.Goedel);
			}

		public void Serialize (TextWriter Output, OutputFormat OutputFormat) {

			StructureWriter StructureWriter = StructureWriter.GetStructureWriter (Output, OutputFormat);
			StructureWriter.StartDocument ();
			foreach (GoedelDomainer._Choice Entry in Top) {
				Entry.Serialize (StructureWriter, true);
				}
			StructureWriter.EndDocument ();
			}


        void Push (GoedelDomainer._Choice Token) {
            _StackItem Item = new _StackItem ();
            Item.State = State;
            Item.Token = Current;

            Stack.Add (Item);

            //Console.WriteLine ("$$$$PUSH {0}", Current);

            Current = Token;
            }

        void Pop () {
            if (Stack.Count == 0) throw new System.Exception ("Internal Parser Error");

            _StackItem Item = Stack[Stack.Count -1];
            State = Item.State;
            Current = Item.Token;

            Stack.RemoveAt (Stack.Count -1 ) ;

            //Console.WriteLine ("$$$$POP {0}", Current);
            }



        public override void Process(TokenType Token, Position Position, string Text) {
            CurrentToken = Token;
            CurrentPosition = Position;
            CurrentText = Text;

            if ((Token == TokenType.SEPARATOR) |
                (Token == TokenType.NULL) |
                (Token == TokenType.COMMENT)) return;
            if (Token == TokenType.INVALID)
                throw new System.Exception("Invalid Token");

            bool Represent = true;

            while (Represent) {
                //Console.WriteLine ("    {3}: {0} {1} '{2}'", Token, Position, Text, State);


                Represent = false;
                switch (State) {
                    case StateCode._Start:                 //      BEGIN
                        if (Token == TokenType.BEGIN) {
                            State = StateCode._Choice;
                            break;
                            }
                        else throw new System.Exception("Parser Error Expected START");

                    case StateCode._Choice:                //      LABEL Class | END
                        if (Token == TokenType.LABEL) {
                            GoedelDomainer.DomainerType LabelType = _Reserved (Text);
                            if (false |
									(LabelType == GoedelDomainer.DomainerType.Group) |
									(LabelType == GoedelDomainer.DomainerType.RR) |
									(LabelType == GoedelDomainer.DomainerType.Q) |
									(LabelType == GoedelDomainer.DomainerType.IG) |
									(LabelType == GoedelDomainer.DomainerType.NA)) {
                                Top.Add(New_Choice(Text));
                                }
                            else {
                                throw new System.Exception("Parser Error Expected [Class]");
                                }
                            break;
                            }
                        if (Token == TokenType.END) {
                            State = StateCode._End;
                            break;
                            }
                        else throw new System.Exception("Parser Error Expected [Class]");

                    case StateCode._End:                   //      -
                        throw new System.Exception("Too Many Closing Braces");

                    case StateCode.Group_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Group Current_Cast = (GoedelDomainer.Group)Current;
                            Current_Cast.Id = Registry.ID(Position, Text, TYPE__GroupT, Current_Cast);
                            State = StateCode.Group__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Group__Id:

                        if (Token == TokenType.BEGIN) {
                            State = StateCode.Group__Members;
                            }
                        else {
							Pop ();
                            Represent = true;
                            }
                        break;
                    case StateCode.Group__Members: 
                        if (Token == TokenType.END) {
                            Pop();
                            break;
                            }

						// Parser transition for LIST $$$$$

                        else if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Group Current_Cast = (GoedelDomainer.Group)Current;
                            Current_Cast.Members.Add ( Registry.REF(Position, Text, TYPE__RRT, Current_Cast ) );
                            break;
                            }

                        break;


                    case StateCode.RR_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.RR Current_Cast = (GoedelDomainer.RR)Current;
                            Current_Cast.Id = Registry.ID(Position, Text, TYPE__RRT, Current_Cast);
                            State = StateCode.RR__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.RR__Id:
                        if (Token == TokenType.INTEGER) {
                            GoedelDomainer.RR Current_Cast = (GoedelDomainer.RR)Current;
                            Current_Cast.Code = Convert.ToInt32(Text);
                            State = StateCode.RR__Code;
                            break;
                            }
                        throw new System.Exception("Expected Integer");

                    case StateCode.RR__Code:
                        if (Token == TokenType.STRING) {
                            GoedelDomainer.RR Current_Cast = (GoedelDomainer.RR)Current;
                            Current_Cast.Description = Text;
                            State = StateCode.RR__Description;
                            break;
                            }
                        throw new System.Exception("Expected String");

                    case StateCode.RR__Description:
                        if (Token == TokenType.STRING) {
                            GoedelDomainer.RR Current_Cast = (GoedelDomainer.RR)Current;
                            Current_Cast.Reference = Text;
                            State = StateCode.RR__Reference;
                            break;
                            }
                        throw new System.Exception("Expected String");

                    case StateCode.RR__Reference:

                        if (Token == TokenType.BEGIN) {
                            State = StateCode.RR__Entries;
                            }
                        else {
							Pop ();
                            Represent = true;
                            }
                        break;
                    case StateCode.RR__Entries: 
                        if (Token == TokenType.END) {
                            Pop();
                            break;
                            }

						// Parser transition for LIST $$$$$

                        else if (Token == TokenType.LABEL) {
							GoedelDomainer.RR Current_Cast = (GoedelDomainer.RR)Current;
                            GoedelDomainer.DomainerType LabelType = _Reserved (Text);
                            if ( false |
									(LabelType == GoedelDomainer.DomainerType.Obsolete) |
									(LabelType == GoedelDomainer.DomainerType.Pseudo) |
									(LabelType == GoedelDomainer.DomainerType.Experimental) |
									(LabelType == GoedelDomainer.DomainerType.IPv4) |
									(LabelType == GoedelDomainer.DomainerType.IPv6) |
									(LabelType == GoedelDomainer.DomainerType.Domain) |
									(LabelType == GoedelDomainer.DomainerType.Mail) |
									(LabelType == GoedelDomainer.DomainerType.NodeID) |
									(LabelType == GoedelDomainer.DomainerType.Byte) |
									(LabelType == GoedelDomainer.DomainerType.Int16) |
									(LabelType == GoedelDomainer.DomainerType.Int32) |
									(LabelType == GoedelDomainer.DomainerType.Time32) |
									(LabelType == GoedelDomainer.DomainerType.Time48) |
									(LabelType == GoedelDomainer.DomainerType.String) |
									(LabelType == GoedelDomainer.DomainerType.Strings) |
									(LabelType == GoedelDomainer.DomainerType.OptionalString) |
									(LabelType == GoedelDomainer.DomainerType.StringX) |
									(LabelType == GoedelDomainer.DomainerType.Binary) |
									(LabelType == GoedelDomainer.DomainerType.Binary8) |
									(LabelType == GoedelDomainer.DomainerType.Binary16) |
									(LabelType == GoedelDomainer.DomainerType.LBinary) |
									(LabelType == GoedelDomainer.DomainerType.Hex) |
									(LabelType == GoedelDomainer.DomainerType.Hex8) |
									(LabelType == GoedelDomainer.DomainerType.Hex16) |
									(LabelType == GoedelDomainer.DomainerType.List) |
									(LabelType == GoedelDomainer.DomainerType.Alt) |
									(LabelType == GoedelDomainer.DomainerType.LByte) |
									(LabelType == GoedelDomainer.DomainerType.LInt16) |
									(LabelType == GoedelDomainer.DomainerType.OptionList) |
									(LabelType == GoedelDomainer.DomainerType.Gateway) ) {
                                Current_Cast.Entries.Add (New_Choice(Text));
                                }
                            else {
								throw new System.Exception("Parser Error Expected [Obsolete Pseudo Experimental IPv4 IPv6 Domain Mail NodeID Byte Int16 Int32 Time32 Time48 String Strings OptionalString StringX Binary Binary8 Binary16 LBinary Hex Hex8 Hex16 List Alt LByte LInt16 OptionList Gateway ]");
								}
							}
                        break;


                    case StateCode.Obsolete_Start:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Pseudo_Start:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Experimental_Start:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.IPv4_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.IPv4 Current_Cast = (GoedelDomainer.IPv4)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.IPv4__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.IPv4__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.IPv6_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.IPv6 Current_Cast = (GoedelDomainer.IPv6)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.IPv6__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.IPv6__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Domain_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Domain Current_Cast = (GoedelDomainer.Domain)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Domain__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Domain__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Mail_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Mail Current_Cast = (GoedelDomainer.Mail)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Mail__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Mail__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.NodeID_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.NodeID Current_Cast = (GoedelDomainer.NodeID)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.NodeID__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.NodeID__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Byte_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Byte Current_Cast = (GoedelDomainer.Byte)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Byte__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Byte__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Int16_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Int16 Current_Cast = (GoedelDomainer.Int16)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Int16__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Int16__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Int32_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Int32 Current_Cast = (GoedelDomainer.Int32)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Int32__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Int32__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Time32_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Time32 Current_Cast = (GoedelDomainer.Time32)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Time32__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Time32__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Time48_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Time48 Current_Cast = (GoedelDomainer.Time48)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Time48__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Time48__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.String_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.String Current_Cast = (GoedelDomainer.String)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.String__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.String__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.OptionalString_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.OptionalString Current_Cast = (GoedelDomainer.OptionalString)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.OptionalString__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.OptionalString__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Strings_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Strings Current_Cast = (GoedelDomainer.Strings)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Strings__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Strings__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.StringX_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.StringX Current_Cast = (GoedelDomainer.StringX)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.StringX__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.StringX__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Binary_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Binary Current_Cast = (GoedelDomainer.Binary)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Binary__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Binary__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Binary8_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Binary8 Current_Cast = (GoedelDomainer.Binary8)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Binary8__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Binary8__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Binary16_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Binary16 Current_Cast = (GoedelDomainer.Binary16)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Binary16__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Binary16__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.LBinary_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.LBinary Current_Cast = (GoedelDomainer.LBinary)Current;
                            Current_Cast.Length = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.LBinary__Length;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.LBinary__Length:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.LBinary Current_Cast = (GoedelDomainer.LBinary)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.LBinary__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.LBinary__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.LByte_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.LByte Current_Cast = (GoedelDomainer.LByte)Current;
                            Current_Cast.Target = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.LByte__Target;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.LByte__Target:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.LByte Current_Cast = (GoedelDomainer.LByte)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.LByte__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.LByte__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.LInt16_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.LInt16 Current_Cast = (GoedelDomainer.LInt16)Current;
                            Current_Cast.Target = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.LInt16__Target;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.LInt16__Target:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.LInt16 Current_Cast = (GoedelDomainer.LInt16)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.LInt16__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.LInt16__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Hex_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Hex Current_Cast = (GoedelDomainer.Hex)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Hex__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Hex__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Hex8_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Hex8 Current_Cast = (GoedelDomainer.Hex8)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Hex8__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Hex8__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Hex16_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Hex16 Current_Cast = (GoedelDomainer.Hex16)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Hex16__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Hex16__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Null_Start:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.OptionList_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.OptionList Current_Cast = (GoedelDomainer.OptionList)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.OptionList__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.OptionList__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Gateway_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Gateway Current_Cast = (GoedelDomainer.Gateway)Current;
                            Current_Cast.Code = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Gateway__Code;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Gateway__Code:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Gateway Current_Cast = (GoedelDomainer.Gateway)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Gateway__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Gateway__Id:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.List_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.List Current_Cast = (GoedelDomainer.List)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.List__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.List__Id:

                        if (Token == TokenType.BEGIN) {
                            State = StateCode.List__Entries;
                            }
                        else {
							Pop ();
                            Represent = true;
                            }
                        break;
                    case StateCode.List__Entries: 
                        if (Token == TokenType.END) {
                            Pop();
                            break;
                            }

						// Parser transition for LIST $$$$$

                        else if (Token == TokenType.LABEL) {
							GoedelDomainer.List Current_Cast = (GoedelDomainer.List)Current;
                            GoedelDomainer.DomainerType LabelType = _Reserved (Text);
                            if ( false |
									(LabelType == GoedelDomainer.DomainerType.IPv4) |
									(LabelType == GoedelDomainer.DomainerType.IPv6) |
									(LabelType == GoedelDomainer.DomainerType.Domain) |
									(LabelType == GoedelDomainer.DomainerType.Mail) |
									(LabelType == GoedelDomainer.DomainerType.Byte) |
									(LabelType == GoedelDomainer.DomainerType.Int16) |
									(LabelType == GoedelDomainer.DomainerType.Int32) |
									(LabelType == GoedelDomainer.DomainerType.String) |
									(LabelType == GoedelDomainer.DomainerType.Strings) |
									(LabelType == GoedelDomainer.DomainerType.Binary) |
									(LabelType == GoedelDomainer.DomainerType.Binary8) |
									(LabelType == GoedelDomainer.DomainerType.Binary16) |
									(LabelType == GoedelDomainer.DomainerType.LBinary) |
									(LabelType == GoedelDomainer.DomainerType.Hex) |
									(LabelType == GoedelDomainer.DomainerType.Hex8) |
									(LabelType == GoedelDomainer.DomainerType.Hex16) ) {
                                Current_Cast.Entries.Add (New_Choice(Text));
                                }
                            else {
								throw new System.Exception("Parser Error Expected [IPv4 IPv6 Domain Mail Byte Int16 Int32 String Strings Binary Binary8 Binary16 LBinary Hex Hex8 Hex16 ]");
								}
							}
                        break;


                    case StateCode.Alt_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Alt Current_Cast = (GoedelDomainer.Alt)Current;
                            Current_Cast.Id = Registry.TOKEN(Position, Text, TYPE__VarT, Current_Cast);
                            State = StateCode.Alt__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Alt__Id:

                        if (Token == TokenType.BEGIN) {
                            State = StateCode.Alt__Entries;
                            }
                        else {
							Pop ();
                            Represent = true;
                            }
                        break;
                    case StateCode.Alt__Entries: 
                        if (Token == TokenType.END) {
                            Pop();
                            break;
                            }

						// Parser transition for LIST $$$$$


						/// Label
                        else {
                            GoedelDomainer.Alt Current_Cast = (GoedelDomainer.Alt)Current;
                            Current_Cast.Entries.Add (NewAltEntry ());
                            Represent = true;
                            }

                        break;


                    case StateCode.AltEntry_Start:
                        if (Token == TokenType.INTEGER) {
                            GoedelDomainer.AltEntry Current_Cast = (GoedelDomainer.AltEntry)Current;
                            Current_Cast.Code = Convert.ToInt32(Text);
                            State = StateCode.AltEntry__Code;
                            break;
                            }
                        throw new System.Exception("Expected Integer");

                    case StateCode.AltEntry__Code:
                        if (Token == TokenType.LABEL) {
							GoedelDomainer.AltEntry Current_Cast = (GoedelDomainer.AltEntry)Current;
                            GoedelDomainer.DomainerType LabelType = _Reserved (Text);
                            if ( false |
									(LabelType == GoedelDomainer.DomainerType.Null) |
									(LabelType == GoedelDomainer.DomainerType.IPv4) |
									(LabelType == GoedelDomainer.DomainerType.IPv6) |
									(LabelType == GoedelDomainer.DomainerType.Domain) |
									(LabelType == GoedelDomainer.DomainerType.Mail) ) {
                                State = StateCode.AltEntry__Choices;
                                Current_Cast.Choices = New_Choice(Text);
                                }
                            else {
                               throw new System.Exception("Parser Error Expected [Null IPv4 IPv6 Domain Mail ]");
                                }
                            break;
                            }
                        else throw new System.Exception("Parser Error Expected [Null IPv4 IPv6 Domain Mail ]");

                    case StateCode.AltEntry__Choices:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.Q_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.Q Current_Cast = (GoedelDomainer.Q)Current;
                            Current_Cast.Id = Registry.ID(Position, Text, TYPE__RRT, Current_Cast);
                            State = StateCode.Q__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.Q__Id:
                        if (Token == TokenType.INTEGER) {
                            GoedelDomainer.Q Current_Cast = (GoedelDomainer.Q)Current;
                            Current_Cast.Code = Convert.ToInt32(Text);
                            State = StateCode.Q__Code;
                            break;
                            }
                        throw new System.Exception("Expected Integer");

                    case StateCode.Q__Code:
                        if (Token == TokenType.STRING) {
                            GoedelDomainer.Q Current_Cast = (GoedelDomainer.Q)Current;
                            Current_Cast.Description = Text;
                            State = StateCode.Q__Description;
                            break;
                            }
                        throw new System.Exception("Expected String");

                    case StateCode.Q__Description:
                        if (Token == TokenType.STRING) {
                            GoedelDomainer.Q Current_Cast = (GoedelDomainer.Q)Current;
                            Current_Cast.Reference = Text;
                            State = StateCode.Q__Reference;
                            break;
                            }
                        throw new System.Exception("Expected String");

                    case StateCode.Q__Reference:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.IG_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.IG Current_Cast = (GoedelDomainer.IG)Current;
                            Current_Cast.Id = Registry.ID(Position, Text, TYPE__RRT, Current_Cast);
                            State = StateCode.IG__Id;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.IG__Id:
                        if (Token == TokenType.INTEGER) {
                            GoedelDomainer.IG Current_Cast = (GoedelDomainer.IG)Current;
                            Current_Cast.Code = Convert.ToInt32(Text);
                            State = StateCode.IG__Code;
                            break;
                            }
                        throw new System.Exception("Expected Integer");

                    case StateCode.IG__Code:
                        if (Token == TokenType.STRING) {
                            GoedelDomainer.IG Current_Cast = (GoedelDomainer.IG)Current;
                            Current_Cast.Description = Text;
                            State = StateCode.IG__Description;
                            break;
                            }
                        throw new System.Exception("Expected String");

                    case StateCode.IG__Description:
                        if (Token == TokenType.STRING) {
                            GoedelDomainer.IG Current_Cast = (GoedelDomainer.IG)Current;
                            Current_Cast.Reference = Text;
                            State = StateCode.IG__Reference;
                            break;
                            }
                        throw new System.Exception("Expected String");

                    case StateCode.IG__Reference:
                        Pop ();
                        Represent = true; 
                        break;
                    case StateCode.NA_Start:
                        if ((Token == TokenType.LABEL) | (Token == TokenType.LITERAL)) {
                            GoedelDomainer.NA Current_Cast = (GoedelDomainer.NA)Current;
                            Current_Cast.Reason = Registry.TOKEN(Position, Text, TYPE__ReasonT, Current_Cast);
                            State = StateCode.NA__Reason;
                            break;
                            }
                        throw new System.Exception("Expected LABEL or LITERAL");

                    case StateCode.NA__Reason:
                        if (Token == TokenType.INTEGER) {
                            GoedelDomainer.NA Current_Cast = (GoedelDomainer.NA)Current;
                            Current_Cast.First = Convert.ToInt32(Text);
                            State = StateCode.NA__First;
                            break;
                            }
                        throw new System.Exception("Expected Integer");

                    case StateCode.NA__First:
                        if (Token == TokenType.INTEGER) {
                            GoedelDomainer.NA Current_Cast = (GoedelDomainer.NA)Current;
                            Current_Cast.Last = Convert.ToInt32(Text);
                            State = StateCode.NA__Last;
                            break;
                            }
                        throw new System.Exception("Expected Integer");

                    case StateCode.NA__Last:
                        Pop ();
                        Represent = true; 
                        break;

                    default:
                        throw new System.Exception("Unreachable code reached");
                    }
                }
            }
        }
	}


