; PATH=/etc/bind/zones/db.cyberishard.com
; 
; DNS Zone file for cyberishard.com using DNS setup Default
;
; This file is automatically generated CHANGES WILL BE OVERWRITTEN!
;
$TTL 600
cyberishard.com.      IN      SOA     dns1.cyberishard.com. hallam.gmail.com. (
                        2024121001       ; serial, todays date + todays serial 
                        3600              ; refresh, seconds
                        1800              ; retry, seconds
                        3600000              ; expire, seconds
                        600 )            ; minimum, seconds

; Additional name servers
cyberishard.com.     IN      NS      dns1.cyberishard.com.
dns1.cyberishard.com.    A 178.62.79.124 
cyberishard.com.     IN      NS      dns2.cyberishard.com.
dns2.cyberishard.com.    A 139.59.200.120 


cyberishard.com.    IN     CAA 0 issue "comodoca.com"
cyberishard.com.    IN     CAA 0 issue "letsencrypt.org"
cyberishard.com.    IN     CAA 0 issuewild  ";"
cyberishard.com.    IN     CAA 0 iodef "mailto:hostmaster@hallambaker.com"

; Hardcoded A records

; For now, forward all mail to a forwarder on the authoritative
cyberishard.com.       IN      MX       1 smtp1.hallambaker.com.


; Host host1.mathmesh.com 178.62.79.124 
cyberishard.com.    A 178.62.79.124 
www.cyberishard.com.    A 178.62.79.124 
http.cyberishard.com.    A 178.62.79.124
https.cyberishard.com.    A 178.62.79.124 
_http._tcp.cyberishard.com.  IN    SRV 1 1 80 host1.mathmesh.com.
_https._tcp.cyberishard.com.   IN   SRV 1 1 443 host1.mathmesh.com.



