; PATH=/etc/bind/zones/db.hallambaker.com
; 
; DNS Zone file for hallambaker.com using DNS setup Default
;
; This file is automatically generated CHANGES WILL BE OVERWRITTEN!
;
$TTL 600
hallambaker.com.      IN      SOA     dns1.hallambaker.com. hallam.gmail.com. (
                        2019031301       ; serial, todays date + todays serial 
                        3600              ; refresh, seconds
                        1800              ; retry, seconds
                        3600000              ; expire, seconds
                        600 )            ; minimum, seconds

; Additional name servers
hallambaker.com.     IN      NS      dns1.hallambaker.com.
dns1.hallambaker.com.    A 178.62.79.124 
hallambaker.com.     IN      NS      dns2.hallambaker.com.
dns2.hallambaker.com.    A 139.59.200.120 


hallambaker.com.    IN     CAA 0 issue "comodoca.com"
hallambaker.com.    IN     CAA 0 issue "letsencrypt.org"
hallambaker.com.    IN     CAA 0 issuewild  ";"
hallambaker.com.    IN     CAA 0 iodef "mailto:hostmaster@hallambaker.com"

; Hardcoded A records
smtp1.hallambaker.com.    A 178.62.79.124

smtp1.hallambaker.com.        IN      TXT    "v=spf1 CloudDroplet ?all"  

; For now, forward all mail to a forwarder on the authoritative
hallambaker.com.       IN      MX       1 smtp1.hallambaker.com.


; Host host1.mathmesh.com 96.237.138.82 
hallambaker.com.    A 96.237.138.82 
www.hallambaker.com.    A 96.237.138.82 
http.hallambaker.com.    A 96.237.138.82
https.hallambaker.com.    A 96.237.138.82 
_http._tcp.hallambaker.com.  IN    SRV 1 1 80 host1.mathmesh.com.
_https._tcp.hallambaker.com.   IN   SRV 1 1 443 host1.mathmesh.com.



