; PATH=/etc/bind/zones/db.letsauthenticate.com
; 
; DNS Zone file for letsauthenticate.com using DNS setup Default
;
; This file is automatically generated CHANGES WILL BE OVERWRITTEN!
;
$TTL 600
letsauthenticate.com.      IN      SOA     dns1.letsauthenticate.com. hallam.gmail.com. (
                        2018082801       ; serial, todays date + todays serial 
                        3600              ; refresh, seconds
                        1800              ; retry, seconds
                        3600000              ; expire, seconds
                        600 )            ; minimum, seconds

; Additional name servers
letsauthenticate.com.     IN      NS      dns1.letsauthenticate.com.
dns1.letsauthenticate.com.    A 178.62.79.124 
letsauthenticate.com.     IN      NS      dns2.letsauthenticate.com.
dns2.letsauthenticate.com.    A 139.59.200.120 


letsauthenticate.com.    IN     CAA 0 issue "comodoca.com"
letsauthenticate.com.    IN     CAA 0 issue "letsencrypt.org"
letsauthenticate.com.    IN     CAA 0 issuewild  ";"
letsauthenticate.com.    IN     CAA 0 iodef "mailto:hostmaster@hallambaker.com"

; Hardcoded A records

; For now, forward all mail to a forwarder on the authoritative
letsauthenticate.com.       IN      MX       1 smtp1.hallambaker.com.


; Host host1.mathmesh.com 173.76.191.93 
letsauthenticate.com.    A 173.76.191.93 
www.letsauthenticate.com.    A 173.76.191.93 
http.letsauthenticate.com.    A 173.76.191.93
https.letsauthenticate.com.    A 173.76.191.93 
_http._tcp.letsauthenticate.com.  IN    SRV 1 1 80 host1.mathmesh.com.
_https._tcp.letsauthenticate.com.   IN   SRV 1 1 443 host1.mathmesh.com.



