; PATH=/etc/bind/zones/db.mplace2.com
; 
; DNS Zone file for mplace2.com using DNS setup Default
;
; This file is automatically generated CHANGES WILL BE OVERWRITTEN!
;
$TTL 600
mplace2.com.      IN      SOA     dns1.mplace2.com. hallam.gmail.com. (
                        2026061001       ; serial, todays date + todays serial 
                        3600              ; refresh, seconds
                        1800              ; retry, seconds
                        3600000              ; expire, seconds
                        600 )            ; minimum, seconds

; Additional name servers
mplace2.com.     IN      NS      dns1.mplace2.com.
dns1.mplace2.com.    A 96.237.102.35 
mplace2.com.     IN      NS      dns2.mplace2.com.
dns2.mplace2.com.    A 96.237.102.36 


mplace2.com.    IN     CAA 0 issue "letsencrypt.org"
mplace2.com.    IN     CAA 0 issuewild  ";"
mplace2.com.    IN     CAA 0 iodef "mailto:hostmaster@hallambaker.com"

; Hardcoded A records

; default mail
mplace2.com.       IN      MX       10 mx01.ionos.com.
mplace2.com.       IN      MX       10 mx00.ionos.com.
mplace2.com. TXT "v=spf1 redirect=_spf.google.com"



; Host host1.cryptomesh.org 96.237.102.35 
mplace2.com.    A 96.237.102.35 
www.mplace2.com.    A 96.237.102.35 
http.mplace2.com.    A 96.237.102.35
https.mplace2.com.    A 96.237.102.35 
_http._tcp.mplace2.com.  IN    SRV 1 1 80 host1.cryptomesh.org.
_https._tcp.mplace2.com.   IN   SRV 1 1 443 host1.cryptomesh.org.


; handles
