; PATH=/etc/bind/zones/db.Default
;
; DNS Zone file for nudeler.com using DNS setup Default
;
; This file is automatically generated CHANGES WILL BE OVERWRITTEN
;
$TTL 600
nudeler.com.      IN      SOA     dns1.nudeler.com. hallam.gmail.com. (
                        2018010601       ; serial, todays date + todays serial 
                        3600              ; refresh, seconds
                        1800              ; retry, seconds
                        3600000              ; expire, seconds
                        600 )            ; minimum, seconds

; Additional name servers
nudeler.com.     IN      NS      dns1.nudeler.com.
dns1.nudeler.com.    A 178.62.79.124 
nudeler.com.     IN      NS      dns2.nudeler.com.
dns2.nudeler.com.    A 139.59.200.120 


nudeler.com.    IN     CAA 0 issue "comodoca.com"
nudeler.com.    IN     CAA 0 issue "letsencrypt.org"
nudeler.com.    IN     CAA 0 issuewild  ";"
nudeler.com.    IN     CAA 0 iodef "mailto:hostmaster@hallambaker.com"

; Hardcoded A records

; For now, forward all mail to a forwarder on the authopritative
nudeler.com.       IN      MX       1 smtp1.hallambaker.com.

; Web redirect to fluxator.org (is in host directory parked/)

; Host host1.mathmesh.com 108.7.198.158
nudeler.com.    A 108.7.198.158 
www.nudeler.com.    A 108.7.198.158 
http.nudeler.com.    A 108.7.198.158
https.nudeler.com.    A 108.7.198.158 
_http._tcp.nudeler.com.  IN    SRV 1 1 80 host1.mathmesh.com.
_https._tcp.nudeler.com.   IN   SRV 1 1 443 host1.mathmesh.com.



