; PATH=/etc/bind/zones/db.prismproof.com
; 
; DNS Zone file for prismproof.com using DNS setup Default
;
; This file is automatically generated CHANGES WILL BE OVERWRITTEN!
;
$TTL 600
prismproof.com.      IN      SOA     dns1.prismproof.com. hallam.gmail.com. (
                        2020071201       ; serial, todays date + todays serial 
                        3600              ; refresh, seconds
                        1800              ; retry, seconds
                        3600000              ; expire, seconds
                        600 )            ; minimum, seconds

; Additional name servers
prismproof.com.     IN      NS      dns1.prismproof.com.
dns1.prismproof.com.    A 178.62.79.124 
prismproof.com.     IN      NS      dns2.prismproof.com.
dns2.prismproof.com.    A 139.59.200.120 


prismproof.com.    IN     CAA 0 issue "comodoca.com"
prismproof.com.    IN     CAA 0 issue "letsencrypt.org"
prismproof.com.    IN     CAA 0 issuewild  ";"
prismproof.com.    IN     CAA 0 iodef "mailto:hostmaster@hallambaker.com"

; Hardcoded A records

; For now, forward all mail to a forwarder on the authoritative
prismproof.com.       IN      MX       1 smtp1.hallambaker.com.


; Host host1.mathmesh.com 96.237.138.82 
prismproof.com.    A 96.237.138.82 
www.prismproof.com.    A 96.237.138.82 
http.prismproof.com.    A 96.237.138.82
https.prismproof.com.    A 96.237.138.82 
_http._tcp.prismproof.com.  IN    SRV 1 1 80 host1.mathmesh.com.
_https._tcp.prismproof.com.   IN   SRV 1 1 443 host1.mathmesh.com.



