; PATH=/etc/bind/zones/db.thresholdmode.com
; 
; DNS Zone file for thresholdmode.com using DNS setup Default
;
; This file is automatically generated CHANGES WILL BE OVERWRITTEN!
;
$TTL 600
thresholdmode.com.      IN      SOA     dns1.thresholdmode.com. hallam.gmail.com. (
                        2020030901       ; serial, todays date + todays serial 
                        3600              ; refresh, seconds
                        1800              ; retry, seconds
                        3600000              ; expire, seconds
                        600 )            ; minimum, seconds

; Additional name servers
thresholdmode.com.     IN      NS      dns1.thresholdmode.com.
dns1.thresholdmode.com.    A 178.62.79.124 
thresholdmode.com.     IN      NS      dns2.thresholdmode.com.
dns2.thresholdmode.com.    A 139.59.200.120 


thresholdmode.com.    IN     CAA 0 issue "comodoca.com"
thresholdmode.com.    IN     CAA 0 issue "letsencrypt.org"
thresholdmode.com.    IN     CAA 0 issuewild  ";"
thresholdmode.com.    IN     CAA 0 iodef "mailto:hostmaster@hallambaker.com"

; Hardcoded A records

; For now, forward all mail to a forwarder on the authoritative
thresholdmode.com.       IN      MX       1 smtp1.hallambaker.com.


; Host host1.mathmesh.com 96.237.138.82 
thresholdmode.com.    A 96.237.138.82 
www.thresholdmode.com.    A 96.237.138.82 
http.thresholdmode.com.    A 96.237.138.82
https.thresholdmode.com.    A 96.237.138.82 
_http._tcp.thresholdmode.com.  IN    SRV 1 1 80 host1.mathmesh.com.
_https._tcp.thresholdmode.com.   IN   SRV 1 1 443 host1.mathmesh.com.



