; PATH=/etc/bind/zones/db.thresholdrise.com
; 
; DNS Zone file for thresholdrise.com using DNS setup Default
;
; This file is automatically generated CHANGES WILL BE OVERWRITTEN!
;
$TTL 600
thresholdrise.com.      IN      SOA     dns1.thresholdrise.com. hallam.gmail.com. (
                        2025012301       ; serial, todays date + todays serial 
                        3600              ; refresh, seconds
                        1800              ; retry, seconds
                        3600000              ; expire, seconds
                        600 )            ; minimum, seconds

; Additional name servers
thresholdrise.com.     IN      NS      dns1.thresholdrise.com.
dns1.thresholdrise.com.    A 178.62.79.124 
thresholdrise.com.     IN      NS      dns2.thresholdrise.com.
dns2.thresholdrise.com.    A 139.59.200.120 


thresholdrise.com.    IN     CAA 0 issue "comodoca.com"
thresholdrise.com.    IN     CAA 0 issue "letsencrypt.org"
thresholdrise.com.    IN     CAA 0 issuewild  ";"
thresholdrise.com.    IN     CAA 0 iodef "mailto:hostmaster@hallambaker.com"

; Hardcoded A records



; default mail
thresholdrise.com.       IN      MX       10 mx01.ionos.com.
thresholdrise.com.       IN      MX       10 mx00.ionos.com.
thresholdrise.com. TXT "v=spf1 redirect=_spf.google.com"



; Host host1.mathmesh.com 178.62.79.124 
thresholdrise.com.    A 178.62.79.124 
www.thresholdrise.com.    A 178.62.79.124 
http.thresholdrise.com.    A 178.62.79.124
https.thresholdrise.com.    A 178.62.79.124 
_http._tcp.thresholdrise.com.  IN    SRV 1 1 80 host1.mathmesh.com.
_https._tcp.thresholdrise.com.   IN   SRV 1 1 443 host1.mathmesh.com.


; handles


