; PATH=/etc/bind/zones/db.mathmesh.com
; 
; DNS Zone file for mathmesh.com using DNS setup Default
;
; This file is automatically generated CHANGES WILL BE OVERWRITTEN!
;
$TTL 600
mathmesh.com.      IN      SOA     dns1.mathmesh.com. hallam.gmail.com. (
                        2026071401       ; serial, todays date + todays serial 
                        3600              ; refresh, seconds
                        1800              ; retry, seconds
                        3600000              ; expire, seconds
                        600 )            ; minimum, seconds

; Additional name servers
mathmesh.com.     IN      NS      dns1.mathmesh.com.
dns1.mathmesh.com.    A 96.237.102.35 
mathmesh.com.     IN      NS      dns2.mathmesh.com.
dns2.mathmesh.com.    A 96.237.102.36 


mathmesh.com.    IN     CAA 0 issue "letsencrypt.org"
mathmesh.com.    IN     CAA 0 issuewild  ";"
mathmesh.com.    IN     CAA 0 iodef "mailto:hostmaster@hallambaker.com"

; Hardcoded A records
host1.mathmesh.org.    A 96.237.102.35
host1.mathmesh.org.        IN      TXT    "v=spf1 Home ?all"  

; default mail
mathmesh.com.       IN      MX       10 mx01.ionos.com.
mathmesh.com.       IN      MX       10 mx00.ionos.com.
mathmesh.com. TXT "v=spf1 redirect=_spf.google.com"



; Host host1.cryptomesh.org 96.237.102.35 
mathmesh.com.    A 96.237.102.35 
; is wildcard
*.mathmesh.com.    A 96.237.102.35 
www.mathmesh.com.    A 96.237.102.35 
http.mathmesh.com.    A 96.237.102.35
https.mathmesh.com.    A 96.237.102.35 
_http._tcp.mathmesh.com.  IN    SRV 1 1 80 host1.cryptomesh.org.
_https._tcp.mathmesh.com.   IN   SRV 1 1 443 host1.cryptomesh.org.


; handles
; mesh handles
